const String onboardinText = 'Lorem ipsum dolor sit amet consectetur. Congue eget\naliquet nullam velit volutpat in viverra. Amet integer\nurna ornare congue ultrices at.';
const String emailText = 'Verify your email\naddress';
const String accountText = 'Please enter your personal information to create\nyour own secure account';
const String getStarted = 'Get Started';
const String welcomeText = 'To Create an account enter a valid email address';
const String welcomeText2 = 'Here’s how to Log in to access your account';
const String welcome = 'Welcome!';
const String regSuccess = "Registration Successful";
const String regSuccessDesc = "You have successfully created an account, click the button below to continue";